"""
Type stubs for PostPyro - async PostgreSQL driver for Python.
"""

from typing import Any, Dict, List, Optional, Union, Iterator, Tuple

__version__: str
apilevel: str
threadsafety: int
paramstyle: str

class DatabaseError(Exception): ...
class InterfaceError(DatabaseError): ...
class DataError(DatabaseError): ...
class OperationalError(DatabaseError): ...
class IntegrityError(DatabaseError): ...
class InternalError(DatabaseError): ...
class ProgrammingError(DatabaseError): ...
class NotSupportedError(DatabaseError): ...

class Row:
    def __len__(self) -> int: ...
    def __getitem__(self, key: Union[int, str]) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __repr__(self) -> str: ...
    def get(self, key: Union[int, str], default: Any = None) -> Any: ...
    def keys(self) -> List[str]: ...
    def values(self) -> List[Any]: ...
    def items(self) -> List[Tuple[str, Any]]: ...
    def to_dict(self) -> Dict[str, Any]: ...

class Transaction:
    async def execute(self, query: str, params: Optional[List[Any]] = None) -> int: ...
    async def query(self, query: str, params: Optional[List[Any]] = None) -> List[Row]: ...
    async def query_one(self, query: str, params: Optional[List[Any]] = None) -> Row: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    def is_active(self) -> bool: ...
    async def __aenter__(self) -> "Transaction": ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool: ...

class Pool:
    async def execute(self, query: str, params: Optional[List[Any]] = None) -> int: ...
    async def query(self, query: str, params: Optional[List[Any]] = None) -> List[Row]: ...
    async def query_one(self, query: str, params: Optional[List[Any]] = None) -> Row: ...
    async def transaction(self) -> Transaction: ...
    async def close(self) -> None: ...
    def is_closed(self) -> bool: ...

async def connect(dsn: str, max_size: int = 10, min_size: int = 0) -> Pool: ...
