"""
Type stubs for PostPyro - async PostgreSQL driver for Python.
"""

from typing import Any, Dict, List, Optional, Union, Iterator, Tuple

__version__: str
apilevel: str
threadsafety: int
paramstyle: str

class DatabaseError(Exception): ...
class InterfaceError(DatabaseError): ...
class DataError(DatabaseError): ...
class OperationalError(DatabaseError): ...
class IntegrityError(DatabaseError): ...
class InternalError(DatabaseError): ...
class ProgrammingError(DatabaseError): ...
class NotSupportedError(DatabaseError): ...

class Row:
    """One result row with name- and index-based column access; returned by `query`/`query_one`, never constructed directly."""

    def __len__(self) -> int: ...
    def __getitem__(self, key: Union[int, str]) -> Any:
        """Column value by position or name; negative indices count from the end, `KeyError`/`IndexError` if not found."""
        ...
    def __iter__(self) -> Iterator[Any]:
        """Iterates values in column order, not (name, value) pairs - use `items()` for that."""
        ...
    def __repr__(self) -> str: ...
    def get(self, key: Union[int, str], default: Any = None) -> Any:
        """Like `__getitem__` but returns `default` instead of raising when the key/index isn't found."""
        ...
    def keys(self) -> List[str]:
        """Column names in order, as a plain `list` - not a dict view, so no set operations or live reflection."""
        ...
    def values(self) -> List[Any]:
        """Column values in order, as a plain `list` - not a dict view."""
        ...
    def items(self) -> List[Tuple[str, Any]]:
        """(name, value) pairs in column order, as a plain `list` of tuples - not a dict view."""
        ...
    def to_dict(self) -> Dict[str, Any]:
        """Copies the row into a real `dict`; if two columns share a name (e.g. an unaliased join), only the last survives."""
        ...

class Transaction:
    """A running transaction from `pool.transaction()`; use as `async with tx:` or call `commit`/`rollback` explicitly."""

    async def execute(self, query: str, params: Optional[List[Any]] = None) -> int:
        """Runs a statement within this transaction and returns rows affected; raises `ProgrammingError` if already committed/rolled back."""
        ...
    async def query(self, query: str, params: Optional[List[Any]] = None) -> List[Row]:
        """Runs a query within this transaction and returns all matching rows."""
        ...
    async def query_one(self, query: str, params: Optional[List[Any]] = None) -> Row:
        """Returns the first matching row; raises `ProgrammingError` on zero rows, silently discards any rows beyond the first."""
        ...
    async def commit(self) -> None:
        """Commits and ends the transaction; a second call raises `ProgrammingError`."""
        ...
    async def rollback(self) -> None:
        """Rolls back and ends the transaction; a second call raises `ProgrammingError`."""
        ...
    def is_active(self) -> bool:
        """True until `commit()`/`rollback()` has completed (including the implicit one from `__aexit__`)."""
        ...
    async def __aenter__(self) -> "Transaction": ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool:
        """Commits on clean exit, rolls back if the block raised; never suppresses the exception (always returns `False`)."""
        ...

class Pool:
    """An async connection pool (`sqlx::PgPool`); obtain via the module-level `connect()`, never constructed directly."""

    async def execute(self, query: str, params: Optional[List[Any]] = None) -> int:
        """Runs a statement on a pooled connection and returns rows affected. `None` params bind as untyped SQL NULL, inferred from context."""
        ...
    async def query(self, query: str, params: Optional[List[Any]] = None) -> List[Row]:
        """Runs a query on a pooled connection and returns all matching rows."""
        ...
    async def query_one(self, query: str, params: Optional[List[Any]] = None) -> Row:
        """Returns the first matching row; raises `ProgrammingError` on zero rows, silently discards any rows beyond the first."""
        ...
    async def transaction(self) -> Transaction:
        """Starts a transaction (a real `BEGIN` round-trip) and returns it; must be awaited before use as `async with`."""
        ...
    async def close(self) -> None:
        """Closes all pooled connections; waits for in-flight queries to finish first."""
        ...
    def is_closed(self) -> bool: ...

async def connect(dsn: str, max_size: int = 10, min_size: int = 0) -> Pool:
    """Opens a connection pool against `dsn`; the only way to obtain a `Pool`."""
    ...
